### ISSUE TITLE
Not able to view notifications

### ISSUE THREAD

**Issue by ramaseshan** [fsmk/fsmk-discuss#2]
My account was for some reason, blocked, and then on revival, I am not able to getting my notifications working.
Attaching the screenshots for the same. Using Firefox 41 on Fedora GNU/Linux.

![screenshot from 2015-11-19 10-38-46](https://cloud.githubusercontent.com/assets/5002019/11262825/dee49546-8ea9-11e5-98a7-60e0e6b8bdd7.png)
![screenshot from 2015-11-19 10-39-01](https://cloud.githubusercontent.com/assets/5002019/11262826/dee4ab9e-8ea9-11e5-8c83-91f325fa136a.png)
![screenshot from 2015-11-19 10-39-03](https://cloud.githubusercontent.com/assets/5002019/11262827/dee7755e-8ea9-11e5-8d1c-64846097e8d2.png)
![screenshot from 2015-11-19 10-39-06](https://cloud.githubusercontent.com/assets/5002019/11262828/deed4b32-8ea9-11e5-9522-40016e23ae1c.png)

Screenshot 1 : I dont get my notification in the notification menu 
Screenshot 2 : My preferences page, which does list out the nofication, but when I click on notification on the side menu, I get error as in Screenshoot 3
Screenshot 4 : Clicking on Trying again, I get this error screen

**Comment by shijiltv** [comment]
I found it working now. Your account was blocked for sometime based on default spam settings. Current spam control is slightly naive and I have to learn more about it before personalizing. I assume that you were not receiving notification due to the same reason and got reset later after I unblocked it. I could not find anything useful from logs available from discourse portal , hence further checking need to be done from system logs. You may reopen this issue if it happen again.
